# 通用配置文件
spring:
  profiles: # 指定默认环境
    active: dev
  application:
    name: lin-pao-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tianlin?serverTimezone=Asia/Shanghai
    username: root
    password: root
  session:
    timeout: 86400  # session过期时间, 两个月
    store-type: redis # session存储类型, 默认存储到服务器内存中，这里改为redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8080
  address: localhost
  servlet:
   session:
    cookie:
      domain: localhost
      same-site: none
      secure: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql日志
  global-config:
    db-config:
     logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
     logic-delete-value: 1 # 逻辑已删除值(默认为 1)
     logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)